VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_BUILD = 3
if VERSION_BUILD == 0:
    VERSION_STRING = "%d.%d" % (VERSION_MAJOR, VERSION_MINOR)
else:
    VERSION_STRING = "%d.%d.%d" % (VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD)
__version__ = VERSION_STRING
